# Site settings
title: Intervention Design, Bob Wassermann
email: bob@wassermann.nl
description: > # this means to ignore newlines until "baseurl:"
  Een micro-blog voor academische doeleinden. Content op deze website zijn deliverables voor minor "Intervention Design"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bobwassermann.me" # the base hostname & protocol for your site
twitter_username: bobwassermann
github_username:  bobwassermann

# Build settings
markdown: kramdown
